import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/page";
import { Roboto } from 'next/font/google'
import Footer from "./Components/Body/Footer/page";
import Lay from "./Libs/page";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ['300'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Online E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Lay>        <Navbar />
        {children}
        <Footer /></Lay>

      </body>
    </html>
  );
}
